# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api/v1

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST http://127.0.0.1:8000/api/v1/advertisements/
Content-Type: application/json
Authorization: Token 6706c9903804d0c61addb4873a9b378ca11fc982

{
  "title": "Кровать IKEA",
  "description": "Срочно, дешего"
}

###

# попытка поменять объявление
PATCH http://127.0.0.1:8000/api/v1/advertisements/3/
Content-Type: application/json
Authorization: Token 6706c9903804d0c61addb4873a9b378ca11fc982

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET http://127.0.0.1:8000/api/v1/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
